engines:
  flog:
    enabled: true
    config:
      score_threshold: 20.0
  rubocop:
    enabled: true
  rubymotion:
    enabled: true
  markdownlint:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.md"
  - "**.css"
  - "**.js"