default: &default
  adapter: postgresql
  encoding: utf8
  host: db
  username: postgres
  password: genupie
  pool: 5

development:
  <<: *default
  database: genupie_development


test:
  <<: *default
  database: genupie_test

production:
  <<: *default
  database: genupie_production
