# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 704298f92304e7f3c05fdf8bf8cfe6f743738133fe80d34508012dd27c668bd84763b86add42eccbc7f3b5358a0df2592b70a9f3a2dd0ebeaa1e690a5de9399b

test:
  secret_key_base: 22066a9e70fc970203a79c28a13d0ea62b3f7c69aa66280692959343e09650f402b3644423d17a9b9d9d10c6455856cfa232de672f4449923338d5ceb0fb4aa0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
